---
- hosts: all
  gather_facts: False
  become: yes
  become_method: sudo
  tasks:
    - name: exec whoami
      raw: whoami
      register: result

    - name: debug result var
      debug: var=result.stdout_lines

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: package
